# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
owo_version=0.13.0+1.21.11

# Mod Properties
mod_version=3.6.0-1.21.11
maven_group=net.tenakt

# Dependencies
fabric_api_version=0.141.6+1.21.11
fabric_language_kotlin_version=1.13.12+kotlin.2.4.10

#name
archives_base_name = Chunk-Destroyer

#java

kotlin.jvm.target.validation.mode=IGNORE
